name: bot_2

on:
  schedule:
    - cron: '20 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Setup Python
        uses: actions/setup-python@v2.2.2

      - name: Setup Dependencies
        run: python3 -m pip install -r requirements.txt

      - name: Run bot
        run: timeout 3500 python3 bot.py || echo 1
        shell: bash
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          UNSPLASH_ACCESS_KEY: ${{ secrets.UNSPLASH_ACCESS_KEY }}
          ENCRYPTION_PASSWD: ${{ secrets.ENCRYPTION_PASSWD }}
