name: list_env
on:
  workflow_dispatch: # Launch manually

jobs:     
  List_env:
    runs-on: ubuntu-latest
    steps:
      - name: List Env
        # Need to base64 encode or github will change the secret value for "***"
        run: sh -c 'ls'
